### ISSUE TITLE
Some components should live in the `mup-web` repo

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#182]
There are a few top-level components under `src/` that I think would be better suited for `mup-web:src/components/` --

```
- Header
- Footer
- LoginForm
- RsvpBox
- RsvpTag
- PageHead?
- PageActionButton?
- ... others?
```

**Comment by mmcgahan** [comment]
agreed on all the listed elements - i wonder if they should live in web-platform-starter, though?

**Comment by sadafie** [comment]
Good question -- using Pro as an example, I think they have built their own header. @mikespencer @acmei Do you use any of these components in Pro? Thoughts on putting in starter repo versus mup-web?

**Comment by mikespencer** [comment]
Nope, pro-web doesn't use any of these. I'd vote to just stick them in mup-web if they are specific to mup-web, otherwise if they are pretty generic and reusable then I would guess meetup-web-components would be best. Otherwise the consuming repo would have to build/customise these components specific to that consuming app anyway, so managing them in the starter repo doesn't seem like the best option for me. Just my thoughts!

**Comment by sadafie** [comment]
Cool, makes sense to me! I'll file a JIRA ticket for a future sprint, but we'll plan this more closely with member eng cc @eilinora to prevent any blockers this time.

**Comment by sadafie** [comment]
Looks like `PageHead` `PageActionButton` and `RsvpBox` were moved to `mup-web` by @eilinora . We still need to move `Header`, `Footer`, `LoginForm`, and `RsvpTag`.

Jira ticket: https://meetup.atlassian.net/browse/WC-47
