### ISSUE TITLE
MOCK Api Data

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#8]
Test cases have a dependency on `meetup-web-platform` for mock api data. I keep going back and forth on this dependency.. see the pro and cons. Should the repo self-contain this mock data so we remove the dependency? Thoughts?

**Comment by mmcgahan** [comment]
Since there is also interest in putting together a library of JS mocks for Meetup Classic, I think it's probably worth splitting the mocks out of `meetup-web-platform` and into a new repo that can be imported more easily by anyone, although with https://github.com/meetup/meetup-web-platform/pull/29, you can now import and use the mocks without any special tooling:

```js
import * as apiMocks from 'meetup-web-platform/lib/util/mocks/api';
```

**Comment by sadafie** [comment]
Fixed
